### ISSUE TITLE
Write js functions documentation

### ISSUE THREAD

**Issue by Mijux** [Autom-A/AutomA-WebUI#15]
Actually there is not documentation, this is a "must have"

**Comment by ElodieFerreira** [comment]
It's may be closed by the PR of the issue #28 ?

**Comment by Mijux** [comment]
The following file: `app.table.component.js` has no documentation for its three functions

**Comment by ElodieFerreira** [comment]
Closed by #35 all documentation is now written and the camelCase is applied in each functions

**Comment by ElodieFerreira** [comment]
Closed by https://github.com/Autom-A/AutomA-WebUI/issues/35 all documentation is now written and the camelCase is applied in each functions
