### ISSUE TITLE
Finish to implement functions to retrieve user input

### ISSUE THREAD

**Issue by Mijux** [Autom-A/AutomA-WebUI#21]
Currently, only the type `list<str>` has a function to retrieve data entered by the user.
TODO: Implement functions to retrieve data for `choice<str>` and `str` type

**Comment by ElodieFerreira** [comment]
Closed by #28

**Comment by ElodieFerreira** [comment]
Closed by https://github.com/Autom-A/AutomA-WebUI/issues/28
